{"name": "test_001[3-4]", "status": "failed", "statusDetails": {"message": "AssertionError: assert (3 + 4) == 3", "trace": "x = 3, y = 4\n\n    @pytest.mark.parametrize('x,y',[(1,2),(3,4),(5,6)])\n    def test_001(x,y):\n>       assert x+y == 3\nE       assert (3 + 4) == 3\n\ntest_01.py:17: AssertionError"}, "parameters": [{"name": "x", "value": "3"}, {"name": "y", "value": "4"}], "start": 1593164088941, "stop": 1593164088941, "uuid": "21a3476f-3c68-4176-809b-3b91df18f989", "historyId": "cc0cfa1dc5d82e4b949a17bf91327b89", "testCaseId": "02922ae489eea352004b3a4d71e86ce3", "fullName": "test_01#test_001", "labels": [{"name": "suite", "value": "test_01"}, {"name": "host", "value": "DESKTOP-GQJA6VO"}, {"name": "thread", "value": "13644-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_01"}]}